<?php

		  
		  
		  
		  <table width="793" height="148" border="0" cellpadding="0" cellspacing="0">
            <tr>
              <td width="39" align="right"><img src="images/sitio/img/hom_01footer.jpg" width="11" height="148"></td>
              <td width="298"><table width="298" height="148" border="0" cellpadding="0" cellspacing="0">
                <tr>
                  <td height="70"><img src="images/sitio/img/hom_recetas.jpg" width="298" height="70"></td>
                </tr>
                <tr>
                  <td width="298" height="78"><script type="text/javascript">
AC_FL_RunContent( 'codebase','http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,19,0','width','298','height','78','src','../swf/hom_bannerrecetas','quality','high','pluginspage','http://www.macromedia.com/go/getflashplayer','wmode','transparent','movie','../swf/hom_bannerrecetas' ); //end AC code
</script><noscript><object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,19,0" width="298" height="78">
                    <param name="movie" value="file:///Z|/quillalles/html/html/swf/hom_bannerrecetas.swf">
                    <param name="quality" value="high">
                    <param name="wmode" value="transparent">
                    <embed src="file:///Z|/quillalles/html/html/swf/hom_bannerrecetas.swf" width="298" height="78" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" wmode="transparent"></embed>
                  </object></noscript></td>
                </tr>
              </table>  </td>
              <td width="207" height="148"><table width="270" height="148" border="0" cellpadding="0" cellspacing="0">
                <tr>
                  <td height="92"><table width="270" height="92" border="0" cellpadding="0" cellspacing="0">
                    <tr>
                      <td width="166"><a href="frutayfibra_consejo1.html" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image16','','images/sitio/img/hom_sabes_ovr.gif',1)"><img src="images/sitio/img/hom_sabes_out.gif" name="Image16" width="166" height="92" border="0"></a></td>
                      <td align="center"><a href="#" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image17','','images/sitio/img/hom_5aldia_ovr.gif',1)"><img src="images/sitio/img/hom_5aldia_out.gif" name="Image17" width="89" height="92" border="0"></a></td>
                    </tr>
                  </table></td>
                </tr>
                <tr>
                  <td height="56"><a href="#" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image15','','images/sitio/img/hom_minitest_ovr.gif',1)"><img src="images/sitio/img/hom_minitest_out.gif" name="Image15" width="255" height="56" border="0"></a></td>
                </tr>
              </table></td>
              <td><script type="text/javascript">
AC_FL_RunContent( 'codebase','http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,19,0','width','186','height','148','src','../swf/hom_comercial','quality','high','pluginspage','http://www.macromedia.com/go/getflashplayer','wmode','transparent','movie','../swf/hom_comercial' ); //end AC code
</script><noscript><object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,19,0" width="186" height="148">
                <param name="movie" value="file:///Z|/quillalles/html/html/swf/hom_comercial.swf">
                <param name="quality" value="high">
                <param name="wmode" value="transparent">
                <embed src="file:///Z|/quillalles/html/html/swf/hom_comercial.swf" width="186" height="148" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" wmode="transparent"></embed>
              </object></noscript></td>
              </tr>
          </table>  
		  


?>