<?php
$url_defecto="http://www.4ruedas.cl";

$dominio= "$url_defecto";
$url ="$url_defecto";
$remitente = "4ruedas.cl";
$mail_remitente ="info@4ruedas.cl";
$color_fondo ="#FFFFFF";
$fondo_tabla ="#FFFFFF";
//#e7db85

$si_ud_no_ve="<font size=\"1\" face=\"Arial, Helvetica, sans-serif\">Si Ud. no puede ver la imagen haga
click ";

$no_desea ="<font face=\"Arial, Helvetica, sans-serif\" size=\"1\" color=\"#000000\">Si 
        no desea seguir recibiedo esta informaci&oacute;n haga click</font>
		<font face=\"Arial, Helvetica, sans-serif\" size=\"1\" > 
        </font>";

$estilos ="<style>
.textos {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 11px;
	color: #000000;
	
	
}
.titulo {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 20px;
	color: #990000;
	
	
}
.bajada {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #000000;
	
	
}


.menu {  font-family: Arial, Helvetica, sans-serif; font-size: 11px; font-weight: bold}

A:hover {color: #990000; text-decoration: none;}
A:visited {color: #990000; text-decoration: none;}


A {color: #990000;text-decoration: none}

body {scrollbar-face-color: #FFFFFF; scrollbar-shadow-color: #FFFFFF; scrollbar-highlight-color: #003366; scrollbar-3dlight-color: #FFFFFF; scrollbar-darkshadow-color: #003366; scrollbar-track-color: #FFFFFF; scrollbar-arrow-color: #003366;}


</style>";

?>